# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Blurter < Formula
  on_macos do
    depends_on "terminal-notifier"
  end

  service do
    run [opt_bin/"blurter", "daemon"]
    keep_alive true
    log_path var/"log/blurter.log"
    error_log_path var/"log/blurter.log"
    working_dir HOMEBREW_PREFIX
    environment_variables PATH: "#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  desc "Local notification daemon: apps spool events, blurter owns the credentials, poli"
  homepage "https://github.com/marcelocantos/blurter"
  url "https://github.com/marcelocantos/blurter/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "2294585bb2e76af5e2edeb3907521c38aec35375f4c73df5934672b943be2e0e"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/blurter/releases/download/v0.1.0/blurter-0.1.0-darwin-arm64.tar.gz"
      sha256 "3b7011e30d6380ca1b4b7050d130a8664987554344e27b83404ce33f097ac357"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/blurter/releases/download/v0.1.0/blurter-0.1.0-linux-amd64.tar.gz"
      sha256 "aa8e3eedc9e47c3bd7aa650243b6b711f7b9f5ea192edecea5382b87a2ac0c3c"
    end

    on_arm do
      url "https://github.com/marcelocantos/blurter/releases/download/v0.1.0/blurter-0.1.0-linux-arm64.tar.gz"
      sha256 "b1f0bd8d6aef24de2282966e2b168395754b7391f2a8b1115a34c0e0ca349426"
    end
  end

  def install
    bin.install "blurter" => "blurter"
  end

  test do
    system bin/"blurter", "--version"
  end
end
