# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Bullseye < Formula
  desc "Mcp server for convergence targets  desired states ranked by wsjf"
  homepage "https://github.com/marcelocantos/bullseye"
  url "https://github.com/marcelocantos/bullseye/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "f2755229260606ced5bcafa6abfbaf60a4c9f32ea37f670bfdb3764a93c135b6"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.1.0/bullseye-0.1.0-darwin-arm64.tar.gz"
      sha256 "73ad441f63226b32605f539d0441c9ff403a4775b35f12cf08ae27588b7fad4d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.1.0/bullseye-0.1.0-linux-amd64.tar.gz"
      sha256 "0976dfa55765bf5e8955786f0fec54068cb9bb8c46c6c1d4d4cdef07be089d83"
    end

    on_arm do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.1.0/bullseye-0.1.0-linux-arm64.tar.gz"
      sha256 "58af706a4dd57d1994bb099e53ec32ba882a04d27c02e28ef29b779c960f19be"
    end
  end

  def install
    bin.install "bullseye" => "bullseye"
  end

  test do
    system bin/"bullseye", "--version"
  end
end
