# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Bullseye < Formula
  desc "Mcp server for managing targets  desired states with dependency tracking and fr"
  homepage "https://github.com/marcelocantos/bullseye"
  url "https://github.com/marcelocantos/bullseye/archive/refs/tags/v0.8.0.tar.gz"
  version "0.8.0"
  sha256 "1086d1641d1176ba6881df71df943ae840a421a0cc498f2d8efcd89086297509"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.8.0/bullseye-0.8.0-darwin-arm64.tar.gz"
      sha256 "cea230088a9a21d4e8caaf0ab540ef72191e6b5d59b26045d4f0c269fad0fe8c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.8.0/bullseye-0.8.0-linux-amd64.tar.gz"
      sha256 "5144c2792f5009e7d315fe20e716073bfd42b7a31c448a15e3ff65c7f37fd7c7"
    end

    on_arm do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.8.0/bullseye-0.8.0-linux-arm64.tar.gz"
      sha256 "531722a60d27ed5031d162c8aa4c03100e2c02d737816df4c9c5bc5038bb974e"
    end
  end

  def install
    bin.install "bullseye" => "bullseye"
  end

  test do
    system bin/"bullseye", "--version"
  end
end
