# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Bullseye < Formula
  desc "Mcp server for managing targets  desired states with dependency tracking and fr"
  homepage "https://github.com/marcelocantos/bullseye"
  url "https://github.com/marcelocantos/bullseye/archive/refs/tags/v0.32.0.tar.gz"
  version "0.32.0"
  sha256 "31ebb2906c368d35d819cd913bc9ac82d224ebda20efec26b7e99c08fa8ce5a0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.32.0/bullseye-0.32.0-darwin-arm64.tar.gz"
      sha256 "fcbf7c0393d669ff09e5a5ba35cdea267a6d915b5196060b8d359ef482e56d5d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.32.0/bullseye-0.32.0-linux-amd64.tar.gz"
      sha256 "64ee12b1e35cddc41a1db1cc7ad557bbca2871cf4403d3682950bd56e0fb64d7"
    end

    on_arm do
      url "https://github.com/marcelocantos/bullseye/releases/download/v0.32.0/bullseye-0.32.0-linux-arm64.tar.gz"
      sha256 "108c7957b1807bad91857461a95fc97d79fa94ec29db24cca1ff74dcf3b788de"
    end
  end

  def install
    bin.install "bullseye" => "bullseye"
  end

  test do
    system bin/"bullseye", "--version"
  end
end
