# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Canopy < Formula
  desc "Mcp server for ast-level multi-language code transformations"
  homepage "https://github.com/marcelocantos/canopy"
  url "https://github.com/marcelocantos/canopy/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "39366697e960c101b51baea6618f3ebf61d24653e0c078e35d947574849bf46e"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/canopy/releases/download/v0.1.0/canopy-0.1.0-darwin-arm64.tar.gz"
      sha256 "0772ab8abdcecb21eef5cbcf0fe389d00f8ee3384a67024252b37afc0c9b8736"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/canopy/releases/download/v0.1.0/canopy-0.1.0-linux-amd64.tar.gz"
      sha256 "56cfe1bac0a19eb00cb47c629ec9174939a030d585cf363229af97469c52a153"
    end

    on_arm do
      url "https://github.com/marcelocantos/canopy/releases/download/v0.1.0/canopy-0.1.0-linux-arm64.tar.gz"
      sha256 "33cd8e961502428dbba9003a9cb2b4a21b87ec02354a0797ac824ad0fa0d409a"
    end
  end

  def install
    bin.install "canopy" => "canopy"
  end

  test do
    system bin/"canopy", "--version"
  end
end
