# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Canopy < Formula
  desc "Mcp server for ast-level multi-language code transformations"
  homepage "https://github.com/marcelocantos/canopy"
  url "https://github.com/marcelocantos/canopy/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "a9c321d169834499329002f172cae80c66306dd41525feb35e66bea97ab49c14"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/canopy/releases/download/v0.2.0/canopy-0.2.0-darwin-arm64.tar.gz"
      sha256 "fd8094ec4449bb9503c38141fe2d6137ffbf904dbfe918c96a7bbb1b2fbfee98"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/canopy/releases/download/v0.2.0/canopy-0.2.0-linux-amd64.tar.gz"
      sha256 "119ce6a34d69ccbf4c53e06d573774180ef3a53a65f91c1a18d023f2b85c59c6"
    end

    on_arm do
      url "https://github.com/marcelocantos/canopy/releases/download/v0.2.0/canopy-0.2.0-linux-arm64.tar.gz"
      sha256 "929de4c2be9ae374ad37983eb305fafeb8a319ef3d61e98d5e690e6c582529d7"
    end
  end

  def install
    bin.install "canopy" => "canopy"
  end

  test do
    system bin/"canopy", "--version"
  end
end
