# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Claudia < Formula
  # Claudia is one long-lived host daemon. The formula ships a service
  # definition so `brew services start claudia` starts the broker on login
  # (🎯T2.7). std_service_path_env FIRST: the daemon spawns provider CLIs
  # Homebrew does not package (claude, grok, cursor, codex), so those
  # per-user dirs stay on PATH — but behind the system path, or anything
  # planted there would win for a background service. TERM/LANG keep
  # Claude's TUI from painting blank under launchd.
  service do
    run [opt_bin/"claudia", "broker", "serve"]
    environment_variables PATH: [
      std_service_path_env,
      "#{Dir.home}/go/bin",
      "#{Dir.home}/.local/bin",
      "#{Dir.home}/.grok/bin",
    ].join(":"), TERM: "xterm-256color", LANG: "en_US.UTF-8"
    keep_alive true
    log_path var/"log/claudia/broker.log"
    error_log_path var/"log/claudia/broker.log"
  end

  desc "Go library that embeds claude, grok, codex, bedrock, ollama, and cursor agents"
  homepage "https://github.com/marcelocantos/claudia"
  url "https://github.com/marcelocantos/claudia/archive/refs/tags/v0.35.0.tar.gz"
  version "0.35.0"
  sha256 "6cfa1655ed6ab953274105cc2b43f6292ccd13d4a77f95bb9de261cf033a190a"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.35.0/claudia-0.35.0-darwin-arm64.tar.gz"
      sha256 "278adbe353b2b77de634c14ed559cf4af67f69167565051bcf32f13b3610c269"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.35.0/claudia-0.35.0-linux-amd64.tar.gz"
      sha256 "cb8a4c9e5dd001df2f6356324f44f266ef4175ecd99f935542202a9983bf60ac"
    end

    on_arm do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.35.0/claudia-0.35.0-linux-arm64.tar.gz"
      sha256 "2eb202e5b5c45d6ec33c21aa3452606f30f28f77f32dc5223e1019e8f5a08c57"
    end
  end

  def install
    bin.install "claudia" => "claudia"
  end

  test do
    system bin/"claudia", "--version"
  end
end
