# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Claudia < Formula
  # Claudia is one long-lived host daemon. The formula ships a service
  # definition so `brew services start claudia` starts the broker on login
  # (🎯T2.7). std_service_path_env FIRST: the daemon spawns provider CLIs
  # Homebrew does not package (claude, grok, cursor, codex), so those
  # per-user dirs stay on PATH — but behind the system path, or anything
  # planted there would win for a background service. TERM/LANG keep
  # Claude's TUI from painting blank under launchd.
  service do
    run [opt_bin/"claudia", "broker", "serve"]
    environment_variables PATH: [
      std_service_path_env,
      "#{Dir.home}/go/bin",
      "#{Dir.home}/.local/bin",
      "#{Dir.home}/.grok/bin",
      "#{Dir.home}/.bun/bin",
    ].join(":"), TERM: "xterm-256color", LANG: "en_US.UTF-8"
    keep_alive true
    log_path var/"log/claudia/broker.log"
    error_log_path var/"log/claudia/broker.log"
  end

  desc "Go library that embeds claude, grok, codex, bedrock, ollama, and cursor agents"
  homepage "https://github.com/marcelocantos/claudia"
  url "https://github.com/marcelocantos/claudia/archive/refs/tags/v0.50.0.tar.gz"
  version "0.50.0"
  sha256 "c283c6f9c97e7538cf7f67750090b0a821f20c04f5d64aac4096ff03c482e87e"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.50.0/claudia-0.50.0-darwin-arm64.tar.gz"
      sha256 "bb70a93a93598f30002b77295312fef1e2556a0cacfdba3961dd4112d37875b3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.50.0/claudia-0.50.0-linux-amd64.tar.gz"
      sha256 "6aa9e08c608418f1d6cdc2b27588799cd4900c102ee64cb5e9e3fdaefad4f22e"
    end

    on_arm do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.50.0/claudia-0.50.0-linux-arm64.tar.gz"
      sha256 "d551e035a105c85aca594c06a47ef012e4efb30642a7859a9f0dc3ce168f0523"
    end
  end

  def install
    bin.install "claudia" => "claudia"
    # 🎯T157: the Bun sidecar that runs plan seats. The broker finds it beside
    # its binary (share/claudia/sidecar) and installs its dependencies there on
    # first start.
    (share/"claudia").install "sidecar"
  end

  test do
    system bin/"claudia", "--version"
  end
end
