# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Claudia < Formula
  # Claudia is one long-lived host daemon. The formula ships a service
  # definition so `brew services start claudia` starts the broker on login
  # (🎯T2.7). std_service_path_env FIRST: the daemon spawns provider CLIs
  # Homebrew does not package (claude, grok, cursor, codex), so those
  # per-user dirs stay on PATH — but behind the system path, or anything
  # planted there would win for a background service. TERM/LANG keep
  # Claude's TUI from painting blank under launchd.
  service do
    run [opt_bin/"claudia", "broker", "serve"]
    environment_variables PATH: [
      std_service_path_env,
      "#{Dir.home}/go/bin",
      "#{Dir.home}/.local/bin",
      "#{Dir.home}/.grok/bin",
    ].join(":"), TERM: "xterm-256color", LANG: "en_US.UTF-8"
    keep_alive true
    log_path var/"log/claudia/broker.log"
    error_log_path var/"log/claudia/broker.log"
  end

  desc "Go library that embeds claude, grok, codex, bedrock, ollama, and cursor agents"
  homepage "https://github.com/marcelocantos/claudia"
  url "https://github.com/marcelocantos/claudia/archive/refs/tags/v0.39.0.tar.gz"
  version "0.39.0"
  sha256 "eeecb5ca4b19edd8651bea1a741082b8552facf2642113ed58af27374d902c54"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.39.0/claudia-0.39.0-darwin-arm64.tar.gz"
      sha256 "b0e239baaef3ee48a5aa6ff7879d58cbaf04ed9078b583ba8f3e0b4869803734"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.39.0/claudia-0.39.0-linux-amd64.tar.gz"
      sha256 "1686781c958bfe2b0832ef6fbc806f664b6ad4787794b24de5671778b80f1685"
    end

    on_arm do
      url "https://github.com/marcelocantos/claudia/releases/download/v0.39.0/claudia-0.39.0-linux-arm64.tar.gz"
      sha256 "13b98b61eb25deb6232a132af5c0144419896b766c7f191496e0a2e4d64c4666"
    end
  end

  def install
    bin.install "claudia" => "claudia"
  end

  test do
    system bin/"claudia", "--version"
  end
end
