# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Crosshair < Formula
  desc "Convergence executor daemon  runs strategies declared on bullseye targets towar"
  homepage "https://github.com/marcelocantos/crosshair"
  url "https://github.com/marcelocantos/crosshair/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "df26b79e15cefccee120eb77907b6ae9848af836cd6e8a99b5f85d8d68f6e6c8"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/crosshair/releases/download/v0.2.0/crosshair-0.2.0-darwin-arm64.tar.gz"
      sha256 "4b921456b04bca9f1ce5cc56721f2e2ad6d895eab51a3b35fd984f505a4f80c5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/crosshair/releases/download/v0.2.0/crosshair-0.2.0-linux-amd64.tar.gz"
      sha256 "fccfe025c5915d59893767829539839c0ace21b7dfb129672a52ef65a16eadd4"
    end

    on_arm do
      url "https://github.com/marcelocantos/crosshair/releases/download/v0.2.0/crosshair-0.2.0-linux-arm64.tar.gz"
      sha256 "ed3be1197fa4cc77b02924f8bd549f3cc5a48b23f5f03b13f2aecbdb6bb816ca"
    end
  end

  def install
    bin.install "crosshair" => "crosshair"
  end

  test do
    system bin/"crosshair", "--version"
  end
end
