# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Crosshair < Formula
  desc "Convergence executor daemon  runs strategies declared on bullseye targets towar"
  homepage "https://github.com/marcelocantos/crosshair"
  url "https://github.com/marcelocantos/crosshair/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "47b1d3c47d6b6b1198b2d129061d565cbc95047f27ff0101d4be0c333d50d594"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/crosshair/releases/download/v0.1.0/crosshair-0.1.0-darwin-arm64.tar.gz"
      sha256 "b3758fb6c416baea4bb79d8f44671936512861cb1dbb648fe076dd8554d3bcf8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/crosshair/releases/download/v0.1.0/crosshair-0.1.0-linux-amd64.tar.gz"
      sha256 "2e8b2dc9e8422109132ab08806f1dc125d6ac7fc11b7294fc1104528c014d73c"
    end

    on_arm do
      url "https://github.com/marcelocantos/crosshair/releases/download/v0.1.0/crosshair-0.1.0-linux-arm64.tar.gz"
      sha256 "47cc0fc6f25f81aad1684f82cde10cacacf960f0a2df1168a887e5d7d01c2559"
    end
  end

  def install
    bin.install "crosshair" => "crosshair"
  end

  test do
    system bin/"crosshair", "--version"
  end
end
