# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cv < Formula
  desc "Build tool with make's dependency-graph model, minus 48 years of accumulated pai"
  homepage "https://github.com/marcelocantos/cv"
  url "https://github.com/marcelocantos/cv/archive/refs/tags/v0.10.0.tar.gz"
  version "0.10.0"
  sha256 "f6e44f97d7c237573bcfa14c44e8a88666e5cb056bb7758b467a773271884480"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/cv/releases/download/v0.10.0/cv-0.10.0-darwin-arm64.tar.gz"
      sha256 "1de83db0a97dc4fdcc3a298ffe6c3b6d07a61ea0ec1392bfa0d2cac7339bb0d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/cv/releases/download/v0.10.0/cv-0.10.0-linux-amd64.tar.gz"
      sha256 "d378f3f413ba715009bac3eab415a3f55e344ae73cdef778cc4e26f9ece1f897"
    end

    on_arm do
      url "https://github.com/marcelocantos/cv/releases/download/v0.10.0/cv-0.10.0-linux-arm64.tar.gz"
      sha256 "8b03423bedcb338dab5ab2e98b9ef0af98296c29f2e3dc5fd398673b6c074fcf"
    end
  end

  def install
    bin.install "cv"
    bash_completion.install "completions/cv.bash" => "cv"
    zsh_completion.install "completions/cv.zsh" => "_cv"
  end

  test do
    (testpath/"cvfile").write <<~EOS
      greeting = world

      hello.txt:
          echo $greeting > $target
    EOS
    system bin/"cv", "-n", "hello.txt"
  end
end
