# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cworkers < Formula
  service do
    run [opt_bin/"cworkers", "serve"]
    keep_alive true
    log_path var/"log/cworkers.log"
    error_log_path var/"log/cworkers.log"
  end

  desc "Task broker for claude code agent sessions  pre-spawned workers, model routing,"
  homepage "https://github.com/marcelocantos/cworkers"
  url "https://github.com/marcelocantos/cworkers/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "54f9dc5f47117402f34cdad45e773f98d68e2c125e1172c91fdbfd39af6fa75c"
  license "NOASSERTION"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/cworkers/releases/download/v0.4.0/cworkers-0.4.0-darwin-arm64.tar.gz"
      sha256 "914beef62b068841d77f3028aef9df14531717abce60d39172503cc8cc3f4246"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/cworkers/releases/download/v0.4.0/cworkers-0.4.0-linux-amd64.tar.gz"
      sha256 "b1c3676996c9c2226e80468f33689cd8fa9b52bd0ed85d2aa826faeb6baa4524"
    end

    on_arm do
      url "https://github.com/marcelocantos/cworkers/releases/download/v0.4.0/cworkers-0.4.0-linux-arm64.tar.gz"
      sha256 "cf44e2f6fdd8c1fb9181a80dedf158f55af56fb7a5b30ae485b51f82069c988b"
    end
  end

  def install
    bin.install "cworkers" => "cworkers"
  end

  test do
    system bin/"cworkers", "--version"
  end
end
