# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Cworkers < Formula
  service do
    run [opt_bin/"cworkers", "serve"]
    keep_alive true
    log_path var/"log/cworkers.log"
    error_log_path var/"log/cworkers.log"
  end

  desc "Task broker for claude code agent sessions  pre-spawned workers, model routing,"
  homepage "https://github.com/marcelocantos/cworkers"
  url "https://github.com/marcelocantos/cworkers/archive/refs/tags/v0.5.0.tar.gz"
  sha256 "55012e203984f1b79a41f89ca464a7a9ef98cddf9f97e1f84f32bb915b17814e"
  license "NOASSERTION"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/cworkers/releases/download/v0.5.0/cworkers-0.5.0-darwin-arm64.tar.gz"
      sha256 "35eff29e26353365084318232ac2014f2b719a8cabc1c7bf3045a232eda103fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/cworkers/releases/download/v0.5.0/cworkers-0.5.0-linux-amd64.tar.gz"
      sha256 "e214934afbc49745575c64257a3a494746e344979aee7fa8a1918c8fe4267432"
    end

    on_arm do
      url "https://github.com/marcelocantos/cworkers/releases/download/v0.5.0/cworkers-0.5.0-linux-arm64.tar.gz"
      sha256 "e845fa54b013cf92cb079deb89474bf2c943aa53e00b726e27a3448f34858a72"
    end
  end

  def install
    bin.install "cworkers" => "cworkers"
  end

  test do
    system bin/"cworkers", "--version"
  end
end
