# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doit < Formula
  desc "Agentic gatekeeper for claude code  three-level policy engine, starlark rules,"
  homepage "https://github.com/marcelocantos/doit"
  url "https://github.com/marcelocantos/doit/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "82d441e1d28550741987d083ca3a0d092c46195978b4ee76ad4a39dba6b71b93"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/doit/releases/download/v0.2.0/doit-0.2.0-darwin-arm64.tar.gz"
      sha256 "b9675119a1bde7e87efc1ff69be423e21aaab661e0b4c0bb055ddd9d6f4a419e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/doit/releases/download/v0.2.0/doit-0.2.0-linux-amd64.tar.gz"
      sha256 "e724a6aa6c95df1816c56d8e85c2906d7cd2b38776518ca0dce711e16d5880be"
    end

    on_arm do
      url "https://github.com/marcelocantos/doit/releases/download/v0.2.0/doit-0.2.0-linux-arm64.tar.gz"
      sha256 "b8ce5bfcf3ae864a34d06374f831fc1b725861540454768094f9ea2ab7b9cb91"
    end
  end

  def install
    bin.install "doit" => "doit"
    bin.install "doit-mcp" => "doit-mcp"
  end

  test do
    system bin/"doit", "--version"
  end
end
