# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Doit < Formula
  desc "Agentic gatekeeper for claude code  three-level policy engine, starlark rules,"
  homepage "https://github.com/marcelocantos/doit"
  url "https://github.com/marcelocantos/doit/archive/refs/tags/v0.4.0.tar.gz"
  version "0.4.0"
  sha256 "01eb3f7a82cfff66df77f8a75424346424a319ee1ec0b7266e72c11e73211eab"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/doit/releases/download/v0.4.0/doit-0.4.0-darwin-arm64.tar.gz"
      sha256 "1c6e4e18005bd96e684832bca1a6d10e52b418b0ba0c224cf22a3886022b9fde"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/doit/releases/download/v0.4.0/doit-0.4.0-linux-amd64.tar.gz"
      sha256 "86b562061d53e3b5c7c2bcb0d16b7ff8ab7d425579aa8a57a797b8eeaf06d6b6"
    end

    on_arm do
      url "https://github.com/marcelocantos/doit/releases/download/v0.4.0/doit-0.4.0-linux-arm64.tar.gz"
      sha256 "3f1ef1bb257ebf6e9c2853a72929140b8e5b58610dc8de4a52c02a9f38be4b1c"
    end
  end

  def install
    bin.install "doit" => "doit"
  end

  test do
    system bin/"doit", "--version"
  end
end
