# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Jevons < Formula
  desc "Personal ai assistant  persistent claude code agents with voice-first web ui, t"
  homepage "https://github.com/marcelocantos/jevons"
  url "https://github.com/marcelocantos/jevons/archive/refs/tags/v0.4.0.tar.gz"
  version "0.4.0"
  sha256 "5c81e102ed805f590bf4a456328daa58b1cdcf92672964bc005f6ca5a30fa837"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.4.0/jevons-0.4.0-darwin-arm64.tar.gz"
      sha256 "689587a87dd630512612c1b3e6cb2825a308e7766356692aa49634b5c92e4798"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.4.0/jevons-0.4.0-linux-amd64.tar.gz"
      sha256 "4bd23d8add394a4f8b536b8e45c4909954daf8d32595b487cccff6a631b932e6"
    end

    on_arm do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.4.0/jevons-0.4.0-linux-arm64.tar.gz"
      sha256 "de20e621959dd2ed3ad23f5afe9625d5bd56f65a71e4fadf408a406c9bca3e60"
    end
  end

  def install
    bin.install "jevonsd" => "jevonsd"
    bin.install "remote" => "remote"
  end

  test do
    system bin/"jevonsd", "--version"
  end
end
