# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Jevons < Formula
  service do
    run [opt_bin/"jevonsd"]
    environment_variables PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:#{Dir.home}/.cargo/bin:#{Dir.home}/.local/bin:#{Dir.home}/.py/bin:#{Dir.home}/go/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    keep_alive true
    log_path var/"log/jevonsd.log"
    error_log_path var/"log/jevonsd.log"
  end

  desc "Personal ai assistant  grok acp overseer, fleet of coding agents, voice-first w"
  homepage "https://github.com/marcelocantos/jevons"
  url "https://github.com/marcelocantos/jevons/archive/refs/tags/v0.19.0.tar.gz"
  version "0.19.0"
  sha256 "0c1e49ec4e67554b8aaa8e9631c8074fb9667e8a1216300c650c9e5393b528a3"
  license "Apache-2.0"

  depends_on "gh"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.19.0/jevons-0.19.0-darwin-arm64.tar.gz"
      sha256 "eb6d765880bee40c816427f8ec2d697acc263c3d818a0dc8c95d9f9040c0a1d6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.19.0/jevons-0.19.0-linux-amd64.tar.gz"
      sha256 "5ee173b4237144bcefd6e0dd2525141b4c1608a26832e8fbfad760c437984fe6"
    end

    on_arm do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.19.0/jevons-0.19.0-linux-arm64.tar.gz"
      sha256 "fefc1f3f9ec9c29208562e3c8c6cda11b009e2c27d56184a67279cdefaa281c4"
    end
  end

  def install
    bin.install "jevonsd" => "jevonsd"
  end

  test do
    system bin/"jevonsd", "--version"
  end
end
