# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Jevons < Formula
  service do
    run [opt_bin/"jevonsd"]
    environment_variables PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:#{Dir.home}/.cargo/bin:#{Dir.home}/.local/bin:#{Dir.home}/.py/bin:#{Dir.home}/go/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    keep_alive true
    log_path var/"log/jevonsd.log"
    error_log_path var/"log/jevonsd.log"
  end

  desc "Personal ai assistant  grok acp overseer, fleet of coding agents, voice-first w"
  homepage "https://github.com/marcelocantos/jevons"
  url "https://github.com/marcelocantos/jevons/archive/refs/tags/v0.12.0.tar.gz"
  version "0.12.0"
  sha256 "20f410fd9d87f7d6f07ad9cb2c8ebd7e8e5bbc4455e1ec0908958c0c83fc3c43"
  license "Apache-2.0"

  depends_on "gh"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.12.0/jevons-0.12.0-darwin-arm64.tar.gz"
      sha256 "9229d39b6d144e3b891870b14e97d2ee7a8ac9a40c755553c60f361e43fab205"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.12.0/jevons-0.12.0-linux-amd64.tar.gz"
      sha256 "4c6201f26ffef33bc0810139c8b8dc8f346085129815b7c7ef39ab8053307921"
    end

    on_arm do
      url "https://github.com/marcelocantos/jevons/releases/download/v0.12.0/jevons-0.12.0-linux-arm64.tar.gz"
      sha256 "3c2811f705687a19b6394a5aaed0160bc137c124e66f379c1d7725d4e01e2176"
    end
  end

  def install
    bin.install "jevonsd" => "jevonsd"
  end

  test do
    system bin/"jevonsd", "--version"
  end
end
