# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mcpbridge < Formula
  service do
    run [opt_bin/"mcpbridge-daemon"]
    keep_alive true
    log_path var/"log/mcpbridge-daemon.log"
    error_log_path var/"log/mcpbridge-daemon.log"
  end

  desc "Transparent wrapper for mcp servers  auto-upgrade without breaking agent sessio"
  homepage "https://github.com/marcelocantos/mcpbridge"
  url "https://github.com/marcelocantos/mcpbridge/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "c766f813b62d55923dc02d88b9c89ec26cf9cb7e73c37471f7cde4321e1a8687"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.1.0/mcpbridge-0.1.0-darwin-arm64.tar.gz"
      sha256 "7780048c2c1f833a431628f82d1097bf3a784c42c527523aca674cad6131de20"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.1.0/mcpbridge-0.1.0-linux-amd64.tar.gz"
      sha256 "fbbb1270924a0f3a178765260dff61b58d98453cacdde76ba64cf78e2a6482f8"
    end

    on_arm do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.1.0/mcpbridge-0.1.0-linux-arm64.tar.gz"
      sha256 "630a36f5ebf272cd47a4c5a2d2c1c195adbd615975987a8e3f4704607c319c33"
    end
  end

  def install
    bin.install "mcpbridge"
    bin.install "mcpbridge-daemon"
  end

  test do
    system "#{bin}/mcpbridge", "--version"
    system "#{bin}/mcpbridge-daemon", "--version"
  end
end
