# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mcpbridge < Formula
  service do
    run [opt_bin/"mcpbridge-daemon"]
    keep_alive true
    log_path var/"log/mcpbridge-daemon.log"
    error_log_path var/"log/mcpbridge-daemon.log"
  end

  desc "Transparent wrapper for mcp servers  auto-upgrade without breaking agent sessio"
  homepage "https://github.com/marcelocantos/mcpbridge"
  url "https://github.com/marcelocantos/mcpbridge/archive/refs/tags/v0.7.0.tar.gz"
  version "0.7.0"
  sha256 "6fe89515aa8007661d7d7d4f10ad8bc80058c1cbefd4460af2b13986a6a172ab"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.7.0/mcpbridge-0.7.0-darwin-arm64.tar.gz"
      sha256 "4f51829db42aecc33aa9c2c4876310d4a42536d72bac70228a57b564fe86b73d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.7.0/mcpbridge-0.7.0-linux-amd64.tar.gz"
      sha256 "0e09972434b8558d5b9e442d4379d5b3841800ae65705e9e9e487b449de7f303"
    end

    on_arm do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.7.0/mcpbridge-0.7.0-linux-arm64.tar.gz"
      sha256 "e5c57d2c047abbdbe5639860688475f5565574e68496e4d28e7059d32097b627"
    end
  end

  def install
    bin.install "mcpbridge"
    bin.install "mcpbridge-daemon"
  end

  test do
    system "#{bin}/mcpbridge", "--version"
    system "#{bin}/mcpbridge-daemon", "--version"
  end
end
