# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mcpbridge < Formula
  service do
    run [opt_bin/"mcpbridge-daemon"]
    keep_alive true
    log_path var/"log/mcpbridge-daemon.log"
    error_log_path var/"log/mcpbridge-daemon.log"
  end

  desc "Transparent wrapper for mcp servers  auto-upgrade without breaking agent sessio"
  homepage "https://github.com/marcelocantos/mcpbridge"
  url "https://github.com/marcelocantos/mcpbridge/archive/refs/tags/v0.6.0.tar.gz"
  version "0.6.0"
  sha256 "dba7ea9547072acda9ce15a1b8b1a1d45a7c93ba5fa0233b61dc0992930432d5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.6.0/mcpbridge-0.6.0-darwin-arm64.tar.gz"
      sha256 "f37e8764bd0bf7a4791e2f5b6464a8504b933cd65a591744e2c739c278b03cd1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.6.0/mcpbridge-0.6.0-linux-amd64.tar.gz"
      sha256 "7d4fcc4a0d07d96ab972abe2133cd4909e6fa346757a60d39fb4a24970fc742c"
    end

    on_arm do
      url "https://github.com/marcelocantos/mcpbridge/releases/download/v0.6.0/mcpbridge-0.6.0-linux-arm64.tar.gz"
      sha256 "b1cf24343ad368e62e31be3f81c178040c334e77b5b3f5cf976f15c5ca8fdf6c"
    end
  end

  def install
    bin.install "mcpbridge"
    bin.install "mcpbridge-daemon"
  end

  test do
    system "#{bin}/mcpbridge", "--version"
    system "#{bin}/mcpbridge-daemon", "--version"
  end
end
