# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mk < Formula
  desc "Build tool with make's dependency-graph model, minus 48 years of accumulated pai"
  homepage "https://github.com/marcelocantos/mk"
  url "https://github.com/marcelocantos/mk/archive/refs/tags/v0.7.0.tar.gz"
  version "0.7.0"
  sha256 "5bcb2eecb6bd74b63b8aca57e8a089976b5a8ae1e9568bead03981c14c55aac6"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/mk/releases/download/v0.7.0/mk-0.7.0-darwin-arm64.tar.gz"
      sha256 "c1769e97328ed13c154d7917c18447797b12cd544da7afcf0ba76459485960fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/mk/releases/download/v0.7.0/mk-0.7.0-linux-amd64.tar.gz"
      sha256 "24c5bb0f949bab7b28b30dfca578a70b9eec18ce8e6460412d57e1f733794a6b"
    end

    on_arm do
      url "https://github.com/marcelocantos/mk/releases/download/v0.7.0/mk-0.7.0-linux-arm64.tar.gz"
      sha256 "d00cd62812b6e7a508736fbe4a9b87ae49bfd8eb248a37afdb0cbeeb8123552a"
    end
  end

  def install
    bin.install "mk"
    bash_completion.install "completions/mk.bash" => "mk"
    zsh_completion.install "completions/mk.zsh" => "_mk"
  end

  test do
    (testpath/"mkfile").write <<~EOS
      greeting = world

      hello.txt:
          echo $greeting > $target
    EOS
    system bin/"mk", "-n", "hello.txt"
  end
end
