# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mnemo < Formula
  depends_on "gh"
  depends_on "uv"
  depends_on "tesseract"
  depends_on "poppler"
  depends_on "mupdf"

  service do
    run [opt_bin/"mnemo"]
    keep_alive true
    log_path var/"log/mnemo.log"
    error_log_path var/"log/mnemo.log"
    working_dir HOMEBREW_PREFIX
    environment_variables PATH: "#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:#{ENV["HOME"]}/.cargo/bin:#{ENV["HOME"]}/.local/bin:#{ENV["HOME"]}/.py/bin:#{ENV["HOME"]}/go/bin:#{ENV["HOME"]}/.claude/local:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  desc "Claude code transcript memory  mcp server for searching past sessions"
  homepage "https://github.com/marcelocantos/mnemo"
  url "https://github.com/marcelocantos/mnemo/archive/refs/tags/v0.73.0.tar.gz"
  version "0.73.0"
  sha256 "e14dcecb5b26d19fef3cc70b416e1288d6f1505b47679624680ca24a62e75175"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/mnemo/releases/download/v0.73.0/mnemo-0.73.0-darwin-arm64.tar.gz"
      sha256 "686000aee72da5ff6ca6fdba8eba6096364ab7cb7d16f893f247db4e4c5873c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/mnemo/releases/download/v0.73.0/mnemo-0.73.0-linux-amd64.tar.gz"
      sha256 "5956f9586c06c32e9d9c8b0bd71af94ac05cdaba8efe4988776d04535c97a42e"
    end

    on_arm do
      url "https://github.com/marcelocantos/mnemo/releases/download/v0.73.0/mnemo-0.73.0-linux-arm64.tar.gz"
      sha256 "4e0083179d476addd1bf0bf7827af0ccd9091f7581b304865008667670cb8d53"
    end
  end

  def install
    bin.install "mnemo" => "mnemo"
  end

  test do
    system bin/"mnemo", "--version"
  end
end
