# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Mnemo < Formula
  depends_on "gh"
  depends_on "uv"
  depends_on "tesseract"
  depends_on "poppler"
  depends_on "mupdf"

  service do
    run [opt_bin/"mnemo"]
    keep_alive true
    log_path var/"log/mnemo.log"
    error_log_path var/"log/mnemo.log"
    working_dir HOMEBREW_PREFIX
    environment_variables PATH: "#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:#{ENV["HOME"]}/.cargo/bin:#{ENV["HOME"]}/.local/bin:#{ENV["HOME"]}/.py/bin:#{ENV["HOME"]}/go/bin:#{ENV["HOME"]}/.claude/local:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  desc "Claude code transcript memory  mcp server for searching past sessions"
  homepage "https://github.com/marcelocantos/mnemo"
  url "https://github.com/marcelocantos/mnemo/archive/refs/tags/v0.33.0.tar.gz"
  version "0.33.0"
  sha256 "a5ff46c6996dedad5464f3e3d38b27b2d7c703c6114740ec6e31e809defa3a47"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/mnemo/releases/download/v0.33.0/mnemo-0.33.0-darwin-arm64.tar.gz"
      sha256 "101e9b22409e371c471ec84b83c755c721a8dfde258b2a404ec3e8e85e98df4f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/mnemo/releases/download/v0.33.0/mnemo-0.33.0-linux-amd64.tar.gz"
      sha256 "8722670cab0d19122c7a38a539f5e0aa36aa5833f6508f562691c5dfd98fa5ec"
    end

    on_arm do
      url "https://github.com/marcelocantos/mnemo/releases/download/v0.33.0/mnemo-0.33.0-linux-arm64.tar.gz"
      sha256 "34e0b94dc510cb434c8b8a0e5fe76d8fc346c1d644f2e4a7d8f66217402c8c3e"
    end
  end

  def install
    bin.install "mnemo" => "mnemo"
  end

  test do
    system bin/"mnemo", "--version"
  end
end
