# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pageflip < Formula
  desc "Capture slides from a screen region whenever they change"
  homepage "https://github.com/marcelocantos/pageflip"
  url "https://github.com/marcelocantos/pageflip/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "e76fed6465d46e119307b3a003afa659e0b22d025fc1c549178e6d4df224edcd"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/pageflip/releases/download/v0.2.0/pageflip-0.2.0-darwin-arm64.tar.gz"
      sha256 "b68fd72b0d2396e90a61cd8b0795d7758ba2a0be65e62b1636a56f082933283c"
    end
  end

  def install
    bin.install "pageflip"
    bin.install "pageflip-feed"
  end

  test do
    system bin/"pageflip", "--version"
    system bin/"pageflip-feed", "--version"
  end
end
