# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pageflip < Formula
  desc "Capture slides from a screen region whenever they change"
  homepage "https://github.com/marcelocantos/pageflip"
  url "https://github.com/marcelocantos/pageflip/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "09ae047c48c182790b14e4ef6c65fdb2984464cba8f46b1b34b67e8b4206577b"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/pageflip/releases/download/v0.1.0/pageflip-0.1.0-darwin-arm64.tar.gz"
      sha256 "c9f002e4659428c06d539272a0ab22fd399f91ae8d6f2e7d9b247ab46b221df1"
    end
  end

  def install
    bin.install "pageflip"
    bin.install "pageflip-feed"
  end

  test do
    system bin/"pageflip", "--version"
    system bin/"pageflip-feed", "--version"
  end
end
