# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pigeon < Formula
  desc "Webtransport relay library (go + swift + kotlin + c + typescript) with e2e encry"
  homepage "https://github.com/marcelocantos/pigeon"
  url "https://github.com/marcelocantos/pigeon/archive/refs/tags/v0.19.0.tar.gz"
  version "0.19.0"
  sha256 "8fb2022d907b70dcdcc59e307fdc8824143ae1052b6a6332f4b93280bc464f62"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/pigeon/releases/download/v0.19.0/pigeon-0.19.0-darwin-arm64.tar.gz"
      sha256 "ca189c38360531b3a11400f26b35720bd148173ddf78131db1d5540add5149d2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/pigeon/releases/download/v0.19.0/pigeon-0.19.0-linux-amd64.tar.gz"
      sha256 "29f892cfc2b92e6fdda3b4cf3ef7cc473279768a19b17044e0182a6227ea1f5c"
    end

    on_arm do
      url "https://github.com/marcelocantos/pigeon/releases/download/v0.19.0/pigeon-0.19.0-linux-arm64.tar.gz"
      sha256 "2cfc448a7f9b753a494b371155ffbfa38342548d2181ed94658d915e6bce30b4"
    end
  end

  def install
    bin.install "pigeon" => "pigeon"
  end

  test do
    system bin/"pigeon", "--version"
  end
end
