# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Pigeon < Formula
  desc "Webtransport relay library (go + swift + kotlin + c + typescript) with e2e encry"
  homepage "https://github.com/marcelocantos/pigeon"
  url "https://github.com/marcelocantos/pigeon/archive/refs/tags/v0.28.0.tar.gz"
  version "0.28.0"
  sha256 "7baf551d0e7fcc07edad4be893b496ce480f8aa130aa5d8769ff876a46628a69"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/pigeon/releases/download/v0.28.0/pigeon-0.28.0-darwin-arm64.tar.gz"
      sha256 "3d9393e99c0f2f9568295911564f995814b7952080fbec6d743dccdef73a005d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/pigeon/releases/download/v0.28.0/pigeon-0.28.0-linux-amd64.tar.gz"
      sha256 "e05668c59101605815f9ebebfbff7318b0f368843e70a46dc37158ac67e34566"
    end

    on_arm do
      url "https://github.com/marcelocantos/pigeon/releases/download/v0.28.0/pigeon-0.28.0-linux-arm64.tar.gz"
      sha256 "9f268800c2d3aea5e626b4b5ce26d4bc29a93f56ebe0ad479cd08d1ac943e4d3"
    end
  end

  def install
    bin.install "pigeon" => "pigeon"
  end

  test do
    system bin/"pigeon", "--version"
  end
end
