# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rustuml < Formula
  desc "Rust port of plantuml  single binary, no runtime dependencies"
  homepage "https://github.com/marcelocantos/rustuml"
  url "https://github.com/marcelocantos/rustuml/archive/refs/tags/v0.3.0.tar.gz"
  version "0.3.0"
  sha256 "5b51ce2bbac91e473a0870753f81de16cd39409833f87598c9e5646b90f37df6"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/rustuml/releases/download/v0.3.0/rustuml-0.3.0-darwin-arm64.tar.gz"
      sha256 "4b1ee0cad511b748824d2629afe55d6e68e6afdc0457b86958d9c84cc070ae1f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/rustuml/releases/download/v0.3.0/rustuml-0.3.0-linux-amd64.tar.gz"
      sha256 "245a7da304fc151c316e21b1b30a03089365906dfbe60651c24e6b5ca62571b7"
    end

    on_arm do
      url "https://github.com/marcelocantos/rustuml/releases/download/v0.3.0/rustuml-0.3.0-linux-arm64.tar.gz"
      sha256 "87d15088090684a563ac96667cfdc836eda1d2ffd74657cd8f025b41ee7a0093"
    end
  end

  def install
    bin.install "rustuml" => "rustuml"
  end

  test do
    system bin/"rustuml", "--version"
  end
end
