# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rustuml < Formula
  desc "Rust port of plantuml  single binary, no runtime dependencies"
  homepage "https://github.com/marcelocantos/rustuml"
  url "https://github.com/marcelocantos/rustuml/archive/refs/tags/v0.5.0.tar.gz"
  version "0.5.0"
  sha256 "26cdfa84aba826761d966bcd915161c7dbe28843185da0006cbdccca3e08b1ec"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/rustuml/releases/download/v0.5.0/rustuml-0.5.0-darwin-arm64.tar.gz"
      sha256 "461a8a92664ac0a87b81078c18f933efc6f7ea7d84bf6c1ff1d9ca1e6b9a82cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/rustuml/releases/download/v0.5.0/rustuml-0.5.0-linux-amd64.tar.gz"
      sha256 "beff2e94a4dcb88556e25982b9a2ae11ce3872eb5096b45149ad5d8b514f303d"
    end

    on_arm do
      url "https://github.com/marcelocantos/rustuml/releases/download/v0.5.0/rustuml-0.5.0-linux-arm64.tar.gz"
      sha256 "71be537f2642b6dd4f4f1539209c7563aae119c193547e84fb3d17302a465774"
    end
  end

  def install
    bin.install "rustuml" => "rustuml"
  end

  test do
    system bin/"rustuml", "--version"
  end
end
