# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Sawmill < Formula
  service do
    run [opt_bin/"sawmill", "serve"]
    keep_alive true
    log_path var/"log/sawmill/sawmill.log"
    error_log_path var/"log/sawmill/sawmill.log"
  end

  desc "Mcp server for ast-level multi-language code transformations"
  homepage "https://github.com/marcelocantos/sawmill"
  url "https://github.com/marcelocantos/sawmill/archive/refs/tags/v0.16.0.tar.gz"
  version "0.16.0"
  sha256 "b0c5e1e92d2fd1207cb46a55d9e3e735330f3638c5abf4d44aa28ed2d96d627b"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/sawmill/releases/download/v0.16.0/sawmill-0.16.0-darwin-arm64.tar.gz"
      sha256 "eae1eb318c69d3f7f7e13bac252cc3acfc387b070c91ba139128d1914a998a72"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/sawmill/releases/download/v0.16.0/sawmill-0.16.0-linux-amd64.tar.gz"
      sha256 "802bdc5f3c120004bc5f83116f635701c3df77d82cf85088568362128b12f9cc"
    end

    on_arm do
      url "https://github.com/marcelocantos/sawmill/releases/download/v0.16.0/sawmill-0.16.0-linux-arm64.tar.gz"
      sha256 "0ba0a43e064ddacc46977af029fcbf967c7207988d49802e1f726849de41b26e"
    end
  end

  def install
    bin.install "sawmill" => "sawmill"
  end

  test do
    system bin/"sawmill", "version"
  end
end
