# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Sawmill < Formula
  service do
    run [opt_bin/"sawmill", "serve"]
    keep_alive true
    log_path var/"log/sawmill/sawmill.log"
    error_log_path var/"log/sawmill/sawmill.log"
  end

  desc "Mcp server for ast-level multi-language code transformations"
  homepage "https://github.com/marcelocantos/sawmill"
  url "https://github.com/marcelocantos/sawmill/archive/refs/tags/v0.18.0.tar.gz"
  version "0.18.0"
  sha256 "60b417f69606e2e02ad6c9e17eadd773e4bbc4849d7b177c65d37f7a533c7b28"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/sawmill/releases/download/v0.18.0/sawmill-0.18.0-darwin-arm64.tar.gz"
      sha256 "a7649bf2a5c8aa174bc1bffe13ea22e5deb5ccc0f8325afe4f2d7096759c706a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/sawmill/releases/download/v0.18.0/sawmill-0.18.0-linux-amd64.tar.gz"
      sha256 "b098c9c749cd45a4e7839643ec8ff55e489e3609129c2dcf5b3f33b04d3d63f7"
    end

    on_arm do
      url "https://github.com/marcelocantos/sawmill/releases/download/v0.18.0/sawmill-0.18.0-linux-arm64.tar.gz"
      sha256 "71519d9510adb665b0116cddc78fed1b8ee6f36f4f72761f6152797f96df32c1"
    end
  end

  def install
    bin.install "sawmill" => "sawmill"
  end

  test do
    system bin/"sawmill", "version"
  end
end
