# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Spyder < Formula
  service do
    run [opt_bin/"spyder", "serve"]
    keep_alive true
    log_path var/"log/spyder.log"
    error_log_path var/"log/spyder.log"
    environment_variables PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  desc "Mcp server for ios and android device orchestration"
  homepage "https://github.com/marcelocantos/spyder"
  url "https://github.com/marcelocantos/spyder/archive/refs/tags/v0.20.0.tar.gz"
  version "0.20.0"
  sha256 "7e1a67aca946e66974c2ca42961743e1b27547b4b57616847fd7e7d1b4aa9ac0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.20.0/spyder-0.20.0-darwin-arm64.tar.gz"
      sha256 "8135183a6c8545dcb76238c3228ec302ca9831912357bb4078fa1b45a72980bf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.20.0/spyder-0.20.0-linux-amd64.tar.gz"
      sha256 "d215b7418c2186c3c25d17e6265cccaef55173600168023fd8319a9abd445795"
    end

    on_arm do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.20.0/spyder-0.20.0-linux-arm64.tar.gz"
      sha256 "38b354cf451e65f4738962bb0333f561fa189893be15983adb3fda471f7aaef8"
    end
  end

  def install
    bin.install "bin/spyder" => "spyder"; libexec.install Dir["libexec/pmd3-bridge"]; libexec.install Dir["libexec/spyder-source"]
  end

  test do
    system bin/"spyder", "--version"
  end
end
