# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Spyder < Formula
  service do
    run [opt_bin/"spyder", "serve"]
    keep_alive true
    log_path var/"log/spyder.log"
    error_log_path var/"log/spyder.log"
    environment_variables PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  desc "Mcp server for ios and android device orchestration"
  homepage "https://github.com/marcelocantos/spyder"
  url "https://github.com/marcelocantos/spyder/archive/refs/tags/v0.16.0.tar.gz"
  version "0.16.0"
  sha256 "76cf51566c57c2247fb34f2fa9926417cb7c41669e5f34fb98c6d51dd62b299d"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.16.0/spyder-0.16.0-darwin-arm64.tar.gz"
      sha256 "34779b40dd7bf06cec88c0fc36105e02c95c8091c92d1dd5d8ee844d44fdd923"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.16.0/spyder-0.16.0-linux-amd64.tar.gz"
      sha256 "dba21c21e41e71743a58174eae7475f8168c136593bf2fe5d030457826a7d992"
    end

    on_arm do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.16.0/spyder-0.16.0-linux-arm64.tar.gz"
      sha256 "6547bdf23f4c77b824cee0833bab7dc8eb961a7ffe08b568b5812a7c86caee65"
    end
  end

  def install
    bin.install "bin/spyder" => "spyder"; libexec.install Dir["libexec/pmd3-bridge"]; libexec.install Dir["libexec/spyder-source"]
  end

  test do
    system bin/"spyder", "--version"
  end
end
