# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Spyder < Formula
  service do
    run [opt_bin/"spyder", "serve"]
    keep_alive true
    log_path var/"log/spyder.log"
    error_log_path var/"log/spyder.log"
    environment_variables PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  end

  def caveats
    <<~EOS
      spyder runs as a persistent HTTP MCP server on :3030.
      It is NOT started automatically on install — start it with:

        brew services start spyder

      Then register it with your agent (Claude Code shown):

        claude mcp add --scope user --transport http spyder http://localhost:3030/mcp

      Verify:

        brew services list | grep spyder    # should be "started"
        lsof -iTCP:3030 -sTCP:LISTEN        # should show spyder

      If MCP tools disappear mid-session, the daemon likely stopped
      — restart with `brew services restart spyder`.

      spyder spawns a bundled `ios` binary (go-ios) as a child
      process for iOS-17+ device discovery. No system LaunchDaemon
      or sudo is required — the tunnel runs in user-space mode.
    EOS
  end

  desc "Mcp server for ios and android device orchestration"
  homepage "https://github.com/marcelocantos/spyder"
  url "https://github.com/marcelocantos/spyder/archive/refs/tags/v0.36.0.tar.gz"
  version "0.36.0"
  sha256 "8a8f7eeaef1c1e56df06f57a6a9d728719dae6e143fe8c422055228127ed9f7e"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/spyder/releases/download/v0.36.0/spyder-0.36.0-darwin-arm64.tar.gz"
      sha256 "677042f8ef8f5ddab36fcdeadb7459dba68cfa25958b7bf9203690abb73706c2"
    end
  end

  def install
    bin.install "bin/spyder" => "spyder"; (libexec/"spyder").install "libexec/spyder/ios"; libexec.install Dir["libexec/spyder-source"]
  end

  test do
    system bin/"spyder", "--version"
  end
end
