# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Sqldeep < Formula
  desc "C++20 transpiler for json5-like sql syntax to standard sql with database-specifi"
  homepage "https://github.com/marcelocantos/sqldeep"
  url "https://github.com/marcelocantos/sqldeep/archive/refs/tags/v0.21.0.tar.gz"
  version "0.21.0"
  sha256 "0ab0d9de291e7f27a7af400863de7b1ef411174ba35f180dac938dba4a11e41c"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/sqldeep/releases/download/v0.21.0/sqldeep-0.21.0-darwin-arm64.tar.gz"
      sha256 "79f8a34dbaadaa1897a17b6c8b4527e0cf0601a10cf2a8b24a92b95effb2bb6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/sqldeep/releases/download/v0.21.0/sqldeep-0.21.0-linux-amd64.tar.gz"
      sha256 "6661f2622d50416e30b6d5efa73939fa575fc6f5d06de1e24eea10aa8b5707ad"
    end

    on_arm do
      url "https://github.com/marcelocantos/sqldeep/releases/download/v0.21.0/sqldeep-0.21.0-linux-arm64.tar.gz"
      sha256 "8eb3491b35e3446473cc2a6737aed694c8f8bf0fdd7fe830ba12a36a1075192f"
    end
  end

  def install
    bin.install "sqldeep" => "sqldeep"
  end

  test do
    system bin/"sqldeep", "--version"
  end
end
