# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class SysinfoMcp < Formula
  desc "Lightweight c mcp server exposing macos system information to ai tools"
  homepage "https://github.com/marcelocantos/sysinfo-mcp"
  url "https://github.com/marcelocantos/sysinfo-mcp/archive/refs/tags/v0.3.0.tar.gz"
  version "0.3.0"
  sha256 "78af6d47bed07c797f6c1417e5b7b3e37fb3c90985c16e3351333dad183090f9"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/sysinfo-mcp/releases/download/v0.3.0/sysinfo-mcp-0.3.0-darwin-arm64.tar.gz"
      sha256 "aff93d95b68c978dc6bc12f023f6c7304cbb8dbfba98dcdc4ea9bbfe90a4a531"
    end
  end

  def install
    bin.install "sysinfo-mcp" => "sysinfo-mcp"
  end

  test do
    system bin/"sysinfo-mcp", "--version"
  end
end
