# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tapper < Formula
  depends_on "docker"
  depends_on "gh"

  def caveats
    <<~EOS
      tapper push runs homebrew-releaser in Docker — start Docker Desktop
      (or your container runtime) before pushing.

      First-time token setup:
        tapper token import-gh
        tapper token verify

      Or store a tap PAT: printf '%s' "$PAT" | tapper token set
    EOS
  end

  desc "Push github releases to any homebrew tap"
  homepage "https://github.com/marcelocantos/tapper"
  url "https://github.com/marcelocantos/tapper/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "c6490fd5819157e506dbf2f84fe24f358e1bf778f1819fdacbd82abcc9402d04"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/tapper/releases/download/v0.2.0/tapper-0.2.0-darwin-arm64.tar.gz"
      sha256 "f36e026d59e7f4cbb1fb2d725f01abcc2b50097b7b176b098b55d4338fdf638d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/tapper/releases/download/v0.2.0/tapper-0.2.0-linux-amd64.tar.gz"
      sha256 "2c928a2cee90e5f2b27160a6f037a3a58bbda6ed89d16a8be5f0b868971c45f9"
    end

    on_arm do
      url "https://github.com/marcelocantos/tapper/releases/download/v0.2.0/tapper-0.2.0-linux-arm64.tar.gz"
      sha256 "17980d5fc09f0312b79bc7ca9ab9117d416a62ed32fbbd104a5bd061cac955fb"
    end
  end

  def install
    bin.install "tapper"
  end

  test do
    system bin/"tapper", "--version"
  end
end
