# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tapper < Formula
  depends_on "docker"
  depends_on "gh"

  def caveats
    <<~EOS
      tapper push runs homebrew-releaser in Docker — start Docker Desktop
      (or your container runtime) before pushing.

  First-time token setup:
    tapper token import-gh
    tapper token verify

  After upgrading from an unsigned build, re-store the token once so
  keychain ACLs match the signed binary:
    tapper token import-gh

  Or store a tap PAT: printf '%s' "$PAT" | tapper token set
    EOS
  end

  desc "Push github releases to any homebrew tap"
  homepage "https://github.com/marcelocantos/tapper"
  url "https://github.com/marcelocantos/tapper/archive/refs/tags/v0.2.1.tar.gz"
  version "0.2.1"
  sha256 "7121c2561ca954b48eeed2d114ce6852e6acdbd928b0bd3789690d346daa9d58"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/tapper/releases/download/v0.2.1/tapper-0.2.1-darwin-arm64.tar.gz"
      sha256 "951dd0a84d16aec82f4f3f4da863d928e1d9340b7ee84eda4b5ca7a04b53c6b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/tapper/releases/download/v0.2.1/tapper-0.2.1-linux-amd64.tar.gz"
      sha256 "0f3045ad73792fda8f571d314f858c660c03e5cec0f1035d5ce2d4e73fb1d64a"
    end

    on_arm do
      url "https://github.com/marcelocantos/tapper/releases/download/v0.2.1/tapper-0.2.1-linux-arm64.tar.gz"
      sha256 "6e1e434f91d371ecea968f15723fec7eaf370fb37ce481f88ad22c21909d59f7"
    end
  end

  def install
    bin.install "tapper"
  end

  test do
    system bin/"tapper", "--version"
  end
end
