# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Tern < Formula
  desc "Websocket relay library (go + swift) with e2e encryption and authenticated pairi"
  homepage "https://github.com/marcelocantos/tern"
  url "https://github.com/marcelocantos/tern/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "10d5be4107fca61b89464544f0b0ad29e936d6df5b556218ea00c5604bf609da"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/tern/releases/download/v0.2.0/tern-0.2.0-darwin-arm64.tar.gz"
      sha256 "8de839e9e8555804dc1f7c3bfad0d6715656a8764df70c15eb72ad98a4154f8e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/tern/releases/download/v0.2.0/tern-0.2.0-linux-amd64.tar.gz"
      sha256 "7198bef9ea922d9c0c71af12ab8fb59e27e5991ad8a887dcf0222c48e8a411b8"
    end

    on_arm do
      url "https://github.com/marcelocantos/tern/releases/download/v0.2.0/tern-0.2.0-linux-arm64.tar.gz"
      sha256 "633b0c0d5330dbe633d824bdd2f678e319a1e1648a4ef94aad63483f268060f4"
    end
  end

  def install
    bin.install "tern" => "tern"
  end

  test do
    system bin/"tern", "--version"
  end
end
