# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vellum < Formula
  depends_on "mermaid-cli"
  depends_on "node"
  depends_on "pandoc"
  depends_on "weasyprint"

  def caveats
    <<~EOS
      vellum is installed with WeasyPrint as the default renderer (BSD-3, open-source).

      To opt into Prince (proprietary, slightly better typography), either:
        - install it from https://www.princexml.com/download/ (free with watermark
          for non-commercial use; commercial licence required otherwise), and
        - set "backend: prince" in ~/.config/vellum/config.yaml, or pass
          --backend prince on the CLI, or supply "backend": "prince" in an
          MCP tool call.

      KaTeX is needed for math rendering:
        npm install -g katex

      Pandoc handles the inverse direction (rich-text → Markdown via
      `vellum import` and the `convert_from_clipboard` MCP tool); it is
      included as a dependency.
    EOS
  end

  desc "Document preparation mcp server  markdown to pdf via goldmark + weasyprint (pri"
  homepage "https://github.com/marcelocantos/vellum"
  url "https://github.com/marcelocantos/vellum/archive/refs/tags/v0.7.0.tar.gz"
  version "0.7.0"
  sha256 "8d223d7cd95f8056b4f849a184cdac1e9639f6732292158f01ab451e98493ea0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.7.0/vellum-0.7.0-darwin-arm64.tar.gz"
      sha256 "1347872b4dd2e2e15e14d4a92406bc28de234c5685231d0541475e15734215fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.7.0/vellum-0.7.0-linux-amd64.tar.gz"
      sha256 "cae8b5c30ab12ea51ddb328f7f72178105513a1d41313e5e141a544bb3c6992d"
    end

    on_arm do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.7.0/vellum-0.7.0-linux-arm64.tar.gz"
      sha256 "39da9dd814585e261e311b669bab5e3240be897c04f0c8cf5ba10996057feaae"
    end
  end

  def install
    bin.install "vellum" => "vellum-bin"
    (bin/"vellum").write <<~SH
      #!/bin/sh
      # Prepend the canonical tool dirs so node, mmdc, and prince
      # resolve regardless of how vellum is launched (terminal,
      # MCP client with a stripped PATH inherited from launchd, …).
      export PATH="#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:/usr/local/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.py/bin:$HOME/go/bin:$PATH"
      exec "#{opt_bin}/vellum-bin" "$@"
    SH
    (bin/"vellum").chmod 0755
  end

  test do
    system bin/"vellum", "--version"
  end
end
