# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vellum < Formula
  depends_on "mermaid-cli"
  depends_on "node"
  depends_on "pandoc"
  depends_on "weasyprint"

  def caveats
    <<~EOS
      vellum is installed with WeasyPrint as the default renderer (BSD-3, open-source).

      To opt into Prince (proprietary, slightly better typography), either:
        - install it from https://www.princexml.com/download/ (free with watermark
          for non-commercial use; commercial licence required otherwise), and
        - set "backend: prince" in ~/.config/vellum/config.yaml, or pass
          --backend prince on the CLI, or supply "backend": "prince" in an
          MCP tool call.

      KaTeX is needed for math rendering:
        npm install -g katex

      Pandoc handles the inverse direction (rich-text → Markdown via
      `vellum import` and the `convert_from_clipboard` MCP tool); it is
      included as a dependency.
    EOS
  end

  desc "Document preparation mcp server  markdown to pdf via goldmark + weasyprint (pri"
  homepage "https://github.com/marcelocantos/vellum"
  url "https://github.com/marcelocantos/vellum/archive/refs/tags/v0.6.0.tar.gz"
  version "0.6.0"
  sha256 "f36aca67ab3dfe80c9a66487704e74d58ce031413875d7f61a0684cc4f34de38"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.6.0/vellum-0.6.0-darwin-arm64.tar.gz"
      sha256 "4f22be2428caa3e9bda2a0126d0a4313452d5d9574e65be3d8807d098cdf885b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.6.0/vellum-0.6.0-linux-amd64.tar.gz"
      sha256 "bee3641c8c8100608fc93488adb8c89d85365b68b997c0078a5536388e3ec978"
    end

    on_arm do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.6.0/vellum-0.6.0-linux-arm64.tar.gz"
      sha256 "d498be1d27d7862156cf8f21f13d293f11d014e444ba7f53741451f6090729d7"
    end
  end

  def install
    bin.install "vellum" => "vellum-bin"
    (bin/"vellum").write <<~SH
      #!/bin/sh
      # Prepend the canonical tool dirs so node, mmdc, and prince
      # resolve regardless of how vellum is launched (terminal,
      # MCP client with a stripped PATH inherited from launchd, …).
      export PATH="#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:/usr/local/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.py/bin:$HOME/go/bin:$PATH"
      exec "#{opt_bin}/vellum-bin" "$@"
    SH
    (bin/"vellum").chmod 0755
  end

  test do
    system bin/"vellum", "--version"
  end
end
