# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vellum < Formula
  depends_on "mermaid-cli"
  depends_on "node"
  depends_on "pandoc"
  depends_on "poppler"
  depends_on "weasyprint"

  service do
    run [opt_bin/"vellum", "serve-view"]
    keep_alive true
    log_path var/"log/vellum-view.log"
    error_log_path var/"log/vellum-view.log"
    working_dir var
  end

  def caveats
    <<~EOS
      vellum is installed with WeasyPrint as the default renderer (BSD-3, open-source).

      To opt into Prince (proprietary, slightly better typography), either:
        - install it from https://www.princexml.com/download/ (free with watermark
          for non-commercial use; commercial licence required otherwise), and
        - set "backend: prince" in ~/.config/vellum/config.yaml, or pass
          --backend prince on the CLI, or supply "backend": "prince" in an
          MCP tool call.

      KaTeX is needed for math rendering:
        npm install -g katex

      Pandoc handles rich-text import (RTF, DOCX, HTML, … → Markdown
      with media extraction). Poppler (pdftoppm/pdftotext) handles PDF
      import (page images + text). Both are formula dependencies.

      Localhost daemon (Markdown view + HTTP MCP at /mcp):
        brew services start vellum
      Binds 127.0.0.1:18742 only. Override with VELLUM_VIEW_ADDR.
      Confirm with: lsof -iTCP:18742 -sTCP:LISTEN
      Do not probe /mcp with bare curl.
      MCP clients: http://127.0.0.1:18742/mcp
        claude mcp add --scope user --transport http vellum http://127.0.0.1:18742/mcp
      Restart the agent session after registration.
    EOS
  end

  desc "Convert markdown, pdf, and rich text via mcp, cli, and clipboard"
  homepage "https://github.com/marcelocantos/vellum"
  url "https://github.com/marcelocantos/vellum/archive/refs/tags/v0.26.0.tar.gz"
  version "0.26.0"
  sha256 "e2be3388b766619797a5f1dc2af81aae183e031359a481a5c611684095e0dbe5"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.26.0/vellum-0.26.0-darwin-arm64.tar.gz"
      sha256 "79ce3b09a2285e96e138a5a7868534504a5bf5489427cd7799e664dc3d87864a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.26.0/vellum-0.26.0-linux-amd64.tar.gz"
      sha256 "aeacec8bac7988f5c7ebfd30c530d4a3e10397949725f59ec8489c18ce2668b3"
    end

    on_arm do
      url "https://github.com/marcelocantos/vellum/releases/download/v0.26.0/vellum-0.26.0-linux-arm64.tar.gz"
      sha256 "96f6794e2f5c95e0309cf32c65f5e6e1ac43c26e6963ad5e61bb27b464e8b743"
    end
  end

  def install
    bin.install "vellum" => "vellum-bin"
    (bin/"vellum").write <<~SH
      #!/bin/sh
      # Prepend the canonical tool dirs so node, mmdc, and prince
      # resolve regardless of how vellum is launched (terminal,
      # MCP client with a stripped PATH inherited from launchd, …).
      export PATH="#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:/usr/local/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.py/bin:$HOME/go/bin:$PATH"
      exec "#{opt_bin}/vellum-bin" "$@"
    SH
    (bin/"vellum").chmod 0755
  end

  test do
    system bin/"vellum", "--version"
  end
end
