# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ytt < Formula
  desc "Fetch youtube video transcripts from the command line"
  homepage "https://github.com/marcelocantos/ytt"
  url "https://github.com/marcelocantos/ytt/archive/refs/tags/v0.12.0.tar.gz"
  version "0.12.0"
  sha256 "0192715dd40e699039aed498ab2807c002c1f24f146f9835d8181bb62b4273a4"
  license "Apache-2.0"

  depends_on "coreutils"
  depends_on "jq"
  depends_on "marcelocantos/tap/blurter"
  depends_on "yq"
  depends_on "yt-dlp"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.12.0/ytt-0.12.0-darwin-arm64.tar.gz"
      sha256 "fe86d3987cde6b81770ccbee520e5e8382aa98470a7170e871bc1fabd005aec6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.12.0/ytt-0.12.0-linux-amd64.tar.gz"
      sha256 "8e6a0da560948056fe70768db8c5786b2b8820675820399606684eb067db3612"
    end

    on_arm do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.12.0/ytt-0.12.0-linux-arm64.tar.gz"
      sha256 "e89bb9220c6d892398d90763e900751b1e70df90a1561df93ccf4916320f4181"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"ytt"
  end

  test do
    assert_match "ytt #{version}", shell_output("#{bin}/ytt --version")
  end
end
