# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ytt < Formula
  desc "Fetch youtube video transcripts from the command line"
  homepage "https://github.com/marcelocantos/ytt"
  url "https://github.com/marcelocantos/ytt/archive/refs/tags/v0.2.0.tar.gz"
  version "0.2.0"
  sha256 "b53458a4720edd308edca9c57342efb16871e6feb8deb02e88c18ff73bcd4ad1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.2.0/ytt-0.2.0-darwin-arm64.tar.gz"
      sha256 "28384786894d2c2de55ef8501b8716e6dbb00ee880edc49ba1d58da6d32da5c0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.2.0/ytt-0.2.0-linux-amd64.tar.gz"
      sha256 "167598c2df26c9ae6f7a26c633ead3b0eb872867055b8400c5d3e7327885d4f8"
    end

    on_arm do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.2.0/ytt-0.2.0-linux-arm64.tar.gz"
      sha256 "a983d24d414448aed0171a2d94bc9f7ea2e08a9f8fed4408e8379cd3e2a1b927"
    end
  end

  def install
    bin.install "ytt"
  end

  test do
    assert_match "ytt #{version}", shell_output("#{bin}/ytt --version")
  end
end
