# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ytt < Formula
  desc "Fetch youtube video transcripts from the command line"
  homepage "https://github.com/marcelocantos/ytt"
  url "https://github.com/marcelocantos/ytt/archive/refs/tags/v0.16.0.tar.gz"
  version "0.16.0"
  sha256 "ddacea1e6eb261999feb41686711ac3190779407b143308c3dddce6f00c4262b"
  license "Apache-2.0"

  depends_on "coreutils"
  depends_on "jq"
  depends_on "marcelocantos/tap/blurter"
  depends_on "yq"
  depends_on "yt-dlp"

  on_macos do
    on_arm do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.16.0/ytt-0.16.0-darwin-arm64.tar.gz"
      sha256 "9de597a81959909ee125c854c4a358e81509930570a4da3acce71942f21eeb74"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.16.0/ytt-0.16.0-linux-amd64.tar.gz"
      sha256 "b533d519f0c92a5791903e191cd7270e2f1b6bc141f73fa90d428f3bcd19999e"
    end

    on_arm do
      url "https://github.com/marcelocantos/ytt/releases/download/v0.16.0/ytt-0.16.0-linux-arm64.tar.gz"
      sha256 "71350d5e8ac0255f8e1ae0a887079105a60942941c72b8734d793c3a17a9a834"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"ytt"
  end

  test do
    assert_match "ytt #{version}", shell_output("#{bin}/ytt --version")
  end
end
